### ISSUE TITLE
Codeclimate setup

### ISSUE THREAD

**Issue by Yawanseh** [PepperBot-co/pepperbot#25]
```
Title: Request to Add CodeClimate Configuration

Body:

Hello,

I would like to propose adding CodeClimate to our project for more comprehensive code quality analysis. Here's the proposed configuration:

```yaml
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- node_modules/
- "**/__tests__/"
```

This configuration will enable the following plugins:

1. **Duplication**: Detects duplicated code. The current configuration is set for JavaScript with a mass threshold of 50. This means that code blocks of 50 tokens or more will be considered as duplicates.
2. **ESLint**: Analyzes the code to find problematic patterns or code that doesn't adhere to certain style guidelines.
3. **FIXME**: Searches for FIXME comments within the codebase.
4. **NodeSecurity**: Checks for packages with known security vulnerabilities.

The configuration also excludes `node_modules/` and test files (`"**/__tests__/")` from the analysis.

By integrating CodeClimate, we can maintain a high standard of code quality, identify issues early, and ensure the maintainability of the project. I believe it would be a beneficial addition.

Looking forward to hearing your thoughts.
